import Head from 'next/head'
import { useState } from 'react';
import Navbar from '../components/Navbar';
import LoginModal from '../components/LoginModal';
import RegistrationModal from '../components/RegistrationModal';
import styles from '../styles/Home.module.css'
import { LoginParameters, RegistrationParameters } from '../types';

interface User {
  name: string;
  username: string;
}

const Home: React.FC = () => {
  const [user, setUser] = useState<User | null>(null);
  const [showLogin, setShowLogin] = useState(false);
  const [showRegistration, setShowRegistration] = useState(false);

  const login = async (p: LoginParameters) => {
    let result = await fetch("http://localhost:8080/api/login", {
      method: "POST",
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(p),
    });

    let json = await result.json();

    console.log(JSON.parse(json));

  }

  const register = async (p: RegistrationParameters) => {
    let result = await fetch("http://localhost:8080/api/register", {
      method: "POST",
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(p)
    });

    let json = await result.json();

    console.log(JSON.parse(json));
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Workout Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar
        onLogin={() => setShowLogin(true) }
        onRegister={() => setShowRegistration(true) }
      />

      <main className={styles.main}>
        <h1>Hello</h1>
        <button onClick={() => { setShowLogin(!showLogin) }}>Login</button>
        <button onClick={() => { setShowRegistration(!showRegistration) }}>Register</button>

        <div id="modal-root" />

        <RegistrationModal
          onClose={() => setShowRegistration(false) }
          onSubmit={(params: RegistrationParameters) => register(params)}
          show={showRegistration}
        />

        <LoginModal
          onClose={() => setShowLogin(false) }
          onSubmit={(params: LoginParameters) => login(params)}
          show={showLogin}
        />
      </main>
    </div>
  )
}

export default Home;
