import Head from 'next/head'
import { useState, useEffect } from 'react';
import Navbar from '../components/Navbar';
import LoginModal from '../components/LoginModal';
import RegistrationModal from '../components/RegistrationModal';
import styles from '../styles/Home.module.css'
import useStore from '../store';

import { fetchUser, logOut } from '../util';

import { User, API_BASE_URL, UtilityParameters } from '../data';

const Home: React.FC = () => {
  const [showLogin, setShowLogin] = useState(false);
  const [showRegistration, setShowRegistration] = useState(false);
  const [user, setUser] = useState<User | null>(null);

  let store: any = useStore();

  let parameters: UtilityParameters = {
    setUser,
    store,
  }

  useEffect(() => {
    if(store.sessionToken !== null) {
      fetchUser(parameters);
    }
  }, [store.sessionToken])

  let main = (
    <main className={styles.main}>
      <h1>Hello { user ? user.name : null}</h1>

      <div id="modal-root" />

      <RegistrationModal
        onClose={() => setShowRegistration(false) }
        onSuccess={() => {
          console.log("sess", store);
          setShowRegistration(false);
          fetchUser(parameters)
        }}
        show={showRegistration}
      />

      <LoginModal
        onClose={() => setShowLogin(false) }
        onSuccess={async() => {
          fetchUser(parameters)
          setShowLogin(false);
        }}
        show={showLogin}
      />
    </main>
  );

  return (
    <div className={styles.container}>
      <Head> <title>Workout Tracker</title> <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar
        loggedIn={user === null}
        onLogout={() => logOut(parameters) }
        onLogin={() => setShowLogin(true) }
        onRegister={() => setShowRegistration(true) }
      />

      { main }

    </div>
  )
}

export default Home;
